### ISSUE TITLE
Enter API / X-Road request body manually

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#15]
AS A Bürokratt user
I WANT TO manually be able to enter query values (request body variables)
SO THAT I CAN define query inputs if #3 is not possible

# AC:

- [ ]

**Comment by turnerrainer** [comment]
@SigritSiht this issue is most likely obsolete as it's done within other developments (Drag & Drop GUI).

**Comment by SigritSiht** [comment]
AC to #12
