### ISSUE TITLE
Update API token value

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#17]
AS A Bürokratt user
I WANT TO have an up-to-date API token value
SO THAT service will be usable whenever end user triggers it

# AC:

- [ ] possibility to change API KEY ID and KEY

**Comment by turnerrainer** [comment]
@SigritSiht Bürokratt user needs API token for what? This issue

1. is either obsolete as this is a technical requirement already covered;
2. has a wrong persona.

**Comment by SigritSiht** [comment]
@turnerrainer Is it still obsolete with the new AC, i.e. entering values that no query can get as input such as API keys created in other systems manually?

**Comment by turnerrainer** [comment]
> @turnerrainer Is it still obsolete with the new AC, i.e. entering values that no query can get as input such as API keys created in other systems manually?

@SigritSiht the API key would be provided by standard Ruuter DSL, the same goes for both long-term (12 months, for example) API keys and short-term (15 or whatever minutes) tokens. If can store this long-term API key in our database or hard-code / store it as a Vault or similar variable, etc. It's still an already existing functionality and only requires DSL(s) for that to be written, not the development of our Bükstack core components or any new ones.

If it remains a separate issue, then fine, but it would make more sense if it was just one of the ACs of some more comprehensive issue.

**Comment by SigritSiht** [comment]
@turnerrainer added it as an AC to #12

**Comment by turnerrainer** [comment]
This issue about the Service Module maintaining third-party API credentials.

Implementation is most likely different for different API-s.

Will probably solve with generic Ruuter templates.
