### ISSUE TITLE
Database refactoring for Service Module

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Service-Module#187]
AS AN Architect
I WANT Service Module Postgres databases and their tables to be refactored
SO THAT they would be compliant with best practices

### Acceptance Criteria

- [ ] All AC from https://github.com/buerokratt/Buerokratt-Architectural-Decision-Records/issues/46 apply

**Comment by 1AhmedYasser** [comment]
@turnerrainer No Liquibase changes are required here, because service module uses both user_db which is defined in chatbot and changes to it are added here https://github.com/buerokratt/Buerokratt-Chatbot/issues/411, and services_db which is added correctly and does not require db changes
