### ISSUE TITLE
Display Service Description

### ISSUE THREAD

**Issue by allarlaaneleht** [buerokratt/Service-Module#203]
AS a Service Manager
I WANT TO view the service description on the Service Module Landing Page
SO THAT I do not have to open the service separately

Related to: https://github.com/buerokratt/Service-Module/issues/11  

### Acceptance criteria:

<s>- [ ] An icon named as "kirjeldus" next to each service name.</s>
- [ ] A tooltip icon created next to each service name.
- [ ] Service description is displayed like a tooltip when hovering the icon.
<s>- [ ] The whole sercive description is displayed in a single box (no scrolling)</s>
- [ ] The service description box max height 200px, if description is longer, then scrollable
- [ ] The user must have an opportunity to copy the text if neccessary.
- [ ] Compatible with mobile version.

**Comment by 1AhmedYasser** [comment]
@allarlaaneleht In Tooltip, its best to have a max height to handle the cases when the description is so long, for example max height `200 px` and if exceeded you can scroll, so it would look good in UI

**Comment by allarlaaneleht** [comment]
@1AhmedYasser Agreed, AC updated.

**Comment by 1AhmedYasser** [comment]
@allarlaaneleht Currently i used this https://react-icons.github.io/react-icons/search/#q=MdOutlineDescription as a description icon, if you wish to change it then please specify the needed icon, you can use https://react-icons.github.io/react-icons/ as a reference, it has a lot of icons

**Comment by ValterAro** [comment]
Short summary: When testing the mobile version on chrome then the description icon is not clickable and does not show the description same on mobile phone.

Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/8fa82047-df14-4393-8d1e-86fc6b4dbca0)

**Comment by ValterAro** [comment]
Seems to work as intended
