### ISSUE TITLE
[BUG] Service can't be linked with intent

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Service-Module#382]
**Bug description:** If I try to link a service to intent I'll get an error message shown in the screen recording

**Expected behavior:** I should get a list of available intents and should get to connect service to intent

**Screenshots:**
https://github.com/user-attachments/assets/50b3c8ee-c304-4080-a54c-29f68aac7cc1

**Additional information:**

**Comment by turnerrainer** [comment]
Works after re-reployment, no coding needed.

**Comment by jaX10bt** [comment]
Works as intended
