### ISSUE TITLE
Configurable styles to distinct chat messages by response types

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Service-Module#43]
- [ ] Bürokratt CSA
- [ ] Bürokratt bot (without Services)
- [ ] Bürokratt Service
- [ ] End User
- [ ] Input provided by the CSA on behalf of the End User

**Comment by SigritSiht** [comment]
Blocked because of UX.

**Comment by SigritSiht** [comment]
Discussed with the UX specialist. Won't implement within this project because it makes the view too complicated.
