### ISSUE TITLE
Service "Population Metrics" created

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#61]
AS a Chatbot trainer
I WANT TO write needed DSL files
SO THAT end users could consume the Service via Bürokratt

### Acceptance Criteria

- [x] query current year for input from an [API endpoint](https://worldtimeapi.org/api/timezone/Europe/Tallinn) "datetime"
- [x] [Population metrics](https://andmed.stat.ee/et/stat/rahvastik__rahvastikunaitajad-ja-koosseis__rahvaarv-ja-rahvastiku-koosseis/RV021) queried for current year, men and women combined, all age groups incl.
- [x] Service intent "SA_Rahvaarv"
- [x] Service answer "Eesti rahvaarv oli {currentYear} 1.jaanuaril {variable}." 
- [ ] Model containing this Service trained.

>Will this be a SA Service or a common Service like the Weather Service? What do you prefer and why? @ffrose @turnerrainer @vmugra 

>>https://andmed.stat.ee/api/v1/et/stat/RV021

```
{
  "query": [
    {
      "code": "Sugu",
      "selection": {
        "filter": "item",
        "values": [
          "1"
        ]
      }
    },
    {
      "code": "Aasta",
      "selection": {
        "filter": "item",
        "values": [
          "2023"
        ]
      }
    },
    {
      "code": "Vanuserühm",
      "selection": {
        "filter": "item",
        "values": [
          "1"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}
```

**Comment by SigritSiht** [comment]
@ffrose Rainer suggested you'd use an [API](http://worldtimeapi.org/) endpoint to retrieve current year (and month where necessary).

**Comment by turnerrainer** [comment]
Previously marked as `obsolete` as https://github.com/buerokratt/Service-Module/issues/62 provides the same result.

**Comment by SigritSiht** [comment]
> Previously marked as `obsolete` as #62 provides the same result.

#63
