### ISSUE TITLE
Confirmation pop-up

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#8]
AS a Bürokratt user
I WANT TO get confirmation that Service is saved
SO THAT I CAN train the model to publish the Service

# AC:

- [ ] pop-up created with confirmation text "Uus teenus on loodud!" (new Service is created)
- [ ] two buttons under confirmation text created:
- Button 1: Liigu edasi mudelit treenima (go to train model)
- Button 2: Treeni hiljem, jäta teenus ootele (train later, save as draft)

**Comment by turnerrainer** [comment]
@SigritSiht should be AC for some GUI issue, not a separate issue of its own.

**Comment by SigritSiht** [comment]
AC of issue #20 added
